# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c8b526858e6778b91c0deb51e7838c586aaac88b5138c870779c2f66fb75380319e26f6a5f6d7bb84e479055ebe85a49fc96430d3344737e5344f8d506f547c

test:
  secret_key_base: 152017a174eb7c9ef0eb93b5ae2f78392eb52818e6c8f6f35fa7fae11c9e736816769cc75c2561fc16a3bb912333e4037bdc6f2081c74411bd7af9f20c6afb4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
